### ISSUE TITLE
hw5 grade

### ISSUE THREAD

**Issue by dcjones** [adonis-wyc/housingrecommendation#2]
The component specification should have at least three components. The one here has only two components, which are named after the two examples given in the assignment ("data manager", "visualization manager").

6/7 points

**Comment by Anthony2018** [comment]
we update the machine_learning.py in  component specification  as the third components.
it will give the prediction price for the land lord who wants to rent the house.

**Comment by dcjones** [comment]
Ok, looks good. 7/7 points
